# Generated by Django 6.0 on 2025-12-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Image/'),
        ),
    ]
